name: Build markdown files

on:
    workflow_dispatch:
    schedule:
        # Runs every 12 hours
        - cron: "0 */12 * * *"

jobs:
    build:
        name: Build markdown files
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v1

            # Open the generator directory
            - name: Open the generator directory
              run: cd generator

            # Install dependencies
            - name: Install dependencies
              run: bun install

            # Run the generator
            - name: Run the generator
              run: bun start

            # Commit the changes
            - uses: EndBug/add-and-commit@v9
              with:
                  message: "Update markdown files"
